-- H2 2.4.240; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'e55b283c80d9f4bb' HASH 'ed8b0d86d3b19e5fe24f55cfdca68dfeacb096c0e9e33fefc1d10d1ed6a95e83' ADMIN;          
CREATE CACHED TABLE "public"."vendors"(
    "id" BINARY(16) NOT NULL,
    "vendor" CHARACTER VARYING(255) NOT NULL,
    "point_person" CHARACTER VARYING(255),
    "email" CHARACTER VARYING(255),
    "location" CHARACTER VARYING(255),
    "miles" INTEGER,
    "products" CHARACTER VARYING(255),
    "is_active" TINYINT DEFAULT 1 NOT NULL,
    "created_at" TIMESTAMP DEFAULT LOCALTIMESTAMP,
    "updated_at" TIMESTAMP ON UPDATE LOCALTIMESTAMP
);    
ALTER TABLE "public"."vendors" ADD CONSTRAINT "public"."CONSTRAINT_1" PRIMARY KEY("id");       
-- 0 +/- SELECT COUNT(*) FROM public.vendors;  
CREATE CACHED TABLE "public"."vendor_transactions"(
    "id" BINARY(16) NOT NULL,
    "vendor_id" BINARY(16) NOT NULL,
    "vendor_name" CHARACTER VARYING(255) NOT NULL,
    "market_date" DATE NOT NULL,
    "present" TINYINT DEFAULT 0,
    "snap" DOUBLE PRECISION,
    "dufb" DOUBLE PRECISION,
    "wdfm_tokens" DOUBLE PRECISION,
    "voucher" DOUBLE PRECISION,
    "reimbursement_due" DOUBLE PRECISION,
    "reported_sales" DOUBLE PRECISION,
    "est_produce_sales" DOUBLE PRECISION,
    "est_num_transactions" BIGINT,
    "custom_data" CHARACTER VARYING,
    "created_at" TIMESTAMP DEFAULT LOCALTIMESTAMP,
    "updated_at" TIMESTAMP ON UPDATE LOCALTIMESTAMP
);         
ALTER TABLE "public"."vendor_transactions" ADD CONSTRAINT "public"."CONSTRAINT_A" PRIMARY KEY("id");           
-- 0 +/- SELECT COUNT(*) FROM public.vendor_transactions;      
CREATE INDEX "public"."vt_vendor_id_date_index" ON "public"."vendor_transactions"("vendor_id" NULLS FIRST, "market_date" NULLS FIRST);         
CREATE INDEX "public"."vt_vendor_name_date_index" ON "public"."vendor_transactions"("vendor_name" NULLS FIRST, "market_date" NULLS FIRST);     
CREATE CACHED TABLE "public"."custom_columns"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "name" CHARACTER VARYING(255),
    "is_required" BOOLEAN DEFAULT FALSE,
    "type" CHARACTER VARYING(255),
    "created_at" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deactivated_at" TIMESTAMP(0)
);     
ALTER TABLE "public"."custom_columns" ADD CONSTRAINT "public"."CONSTRAINT_19" PRIMARY KEY("id");               
-- 0 +/- SELECT COUNT(*) FROM public.custom_columns;           
CREATE INDEX "public"."cc_name_idx" ON "public"."custom_columns"("name" NULLS FIRST);          
CREATE CACHED TABLE "public"."vendor_defaults"(
    "id" BINARY(16) NOT NULL,
    "vendor_id" BINARY(16) NOT NULL,
    "pct_handmade" DECIMAL(5, 2) DEFAULT 0.00 NOT NULL,
    "pct_agricultural" DECIMAL(5, 2) DEFAULT 0.00 NOT NULL,
    "pct_prepared_food" DECIMAL(5, 2) DEFAULT 0.00 NOT NULL,
    "pct_cottage_goods" DECIMAL(5, 2) DEFAULT 0.00 NOT NULL,
    "pct_manufactured" DECIMAL(5, 2) DEFAULT 0.00 NOT NULL
); 
ALTER TABLE "public"."vendor_defaults" ADD CONSTRAINT "public"."CONSTRAINT_8" PRIMARY KEY("id");               
-- 0 +/- SELECT COUNT(*) FROM public.vendor_defaults;          
CREATE CACHED TABLE "public"."category_labels"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) DEFAULT ON NULL NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "color" CHARACTER VARYING(20)
);       
ALTER TABLE "public"."category_labels" ADD CONSTRAINT "public"."CONSTRAINT_C" PRIMARY KEY("id");               
-- 5 +/- SELECT COUNT(*) FROM public.category_labels;          
INSERT INTO "public"."category_labels" VALUES
(1, 'Woman Owned', '#84cc16'),
(2, 'BIPOC Owned', '#eab308'),
(3, 'Farmer', '#f97316'),
(4, 'Veteran Owned', '#ef4444'),
(5, 'Produce', '#14b8a6');              
CREATE CACHED TABLE "public"."vendor_category_labels"(
    "vendor_id" BINARY(16) NOT NULL,
    "label_id" BIGINT NOT NULL
);  
ALTER TABLE "public"."vendor_category_labels" ADD CONSTRAINT "public"."CONSTRAINT_7" PRIMARY KEY("vendor_id", "label_id");     
-- 0 +/- SELECT COUNT(*) FROM public.vendor_category_labels;   
ALTER TABLE "public"."vendor_defaults" ADD CONSTRAINT "public"."check_core_total" CHECK((((("pct_handmade" + "pct_agricultural") + "pct_prepared_food") + "pct_cottage_goods") + "pct_manufactured") = 100.00) NOCHECK;        
ALTER TABLE "public"."custom_columns" ADD CONSTRAINT "public"."CONSTRAINT_193" CHECK("type" IN('text', 'number', 'boolean', 'usd')) NOCHECK;   
ALTER TABLE "public"."custom_columns" ADD CONSTRAINT "public"."CONSTRAINT_193B" UNIQUE NULLS DISTINCT ("name");
ALTER TABLE "public"."vendor_transactions" ADD CONSTRAINT "public"."vt_vendor_id_market_date_uindex" UNIQUE NULLS DISTINCT ("vendor_id", "market_date");       
ALTER TABLE "public"."vendor_defaults" ADD CONSTRAINT "public"."CONSTRAINT_88" UNIQUE NULLS DISTINCT ("vendor_id");            
ALTER TABLE "public"."vendors" ADD CONSTRAINT "public"."vendors_vendor_uindex" UNIQUE NULLS DISTINCT ("vendor");               
ALTER TABLE "public"."vendor_category_labels" ADD CONSTRAINT "public"."CONSTRAINT_78" FOREIGN KEY("vendor_id") REFERENCES "public"."vendors"("id") NOCHECK;    
ALTER TABLE "public"."vendor_category_labels" ADD CONSTRAINT "public"."CONSTRAINT_787" FOREIGN KEY("label_id") REFERENCES "public"."category_labels"("id") NOCHECK;            
ALTER TABLE "public"."vendor_defaults" ADD CONSTRAINT "public"."fk_vendor" FOREIGN KEY("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE CASCADE NOCHECK;             
ALTER TABLE "public"."vendor_transactions" ADD CONSTRAINT "public"."CONSTRAINT_A2" FOREIGN KEY("vendor_id") REFERENCES "public"."vendors"("id") NOCHECK;       
