package com.csi43C9.baylor.farmers_market.security.jwt;

import tools.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.security.core.AuthenticationException;

import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;

/*
 * Unit tests for the AuthEntryPointJwt class, which handles unauthorized authentication
 * attempts by returning a structured error response. These tests ensure that when an
 * unauthenticated user tries to access a secured resource, the application responds
 * with the correct HTTP status, content type, and a detailed JSON error body.
 */
@ExtendWith(MockitoExtension.class)
class AuthEntryPointJwtTest {

    // Mock HttpServletRequest to simulate incoming requests
    @Mock
    private HttpServletRequest request;

    // Mock HttpServletResponse to capture the response generated by the entry point
    private MockHttpServletResponse response;

    // Mock AuthenticationException to simulate an authentication failure
    @Mock
    private AuthenticationException authException;

    // The AuthEntryPointJwt instance under test
    private AuthEntryPointJwt authEntryPointJwt;

    /**
     * Set up the test environment before each test method.
     * Initializes AuthEntryPointJwt and MockHttpServletResponse.
     */
    @BeforeEach
    void setUp() {
        authEntryPointJwt = new AuthEntryPointJwt();
        response = new MockHttpServletResponse();
    }

    /**
     * Tests the `commence` method to ensure it correctly handles an unauthorized access attempt.
     * It sets up a mock request and authentication exception, invokes the `commence` method,
     * and then verifies that the response has:
     * - HTTP status 401 (Unauthorized)
     * - Content type "application/json"
     * - A JSON body containing the expected status, error message, and request path.
     *
     * @throws Exception if any I/O error occurs during response writing or JSON processing.
     */
    @Test
    void testCommence() throws Exception {
        // Given: Set up the mock request and authentication exception behavior
        String requestURI = "/api/test";
        String errorMessage = "Full authentication is required to access this resource";
        // Simulate the request's servlet path
        when(request.getServletPath()).thenReturn(requestURI);
        // Simulate the authentication exception's message
        when(authException.getMessage()).thenReturn(errorMessage);

        // When: Invoke the commence method of the authentication entry point
        authEntryPointJwt.commence(request, response, authException);

        // Then: Verify the response properties
        // Assert that the HTTP status code is 401 (Unauthorized)
        assertThat(response.getStatus()).isEqualTo(HttpServletResponse.SC_UNAUTHORIZED);
        // Assert that the content type of the response is JSON
        assertThat(response.getContentType()).isEqualTo("application/json");

        // Use ObjectMapper to parse the JSON response body
        ObjectMapper mapper = new ObjectMapper();
        // The responseBody map will hold key-value pairs from the JSON,
        // with values typed as Object to accommodate both Strings and Integers.
        Map<String, Object> responseBody;
        // Suppress unchecked warning for map type inference from readValue
        // noinspection unchecked
        responseBody = mapper.readValue(response.getContentAsString(), HashMap.class);

        // Assert that the 'status' field in the JSON body matches the Unauthorized status
        assertThat(responseBody.get("status")).isEqualTo(HttpServletResponse.SC_UNAUTHORIZED);
        // Assert the 'error' message in the JSON body
        assertThat(responseBody.get("error")).isEqualTo("Unauthorized");
        // Assert that the 'message' field in the JSON body is a String and matches the expected error message
        assertThat(responseBody.get("message")).isInstanceOf(String.class).isEqualTo(errorMessage);
        // Assert that the 'path' field in the JSON body matches the request URI
        assertThat(responseBody.get("path")).isEqualTo(requestURI);
    }
}
